export const userActionTypes = {
  GET_USERS: 'GET_USER',
  GET_USERS_SUCCESS: 'GET_USER_SUCCESS',
  GET_USERS_FAIL: 'GET_USER_FAIL',

  GET_USER_BY_ID: 'GET_USER_BY_ID',
  GET_USER_BY_ID_SUCCESS: 'GET_USER_BY_ID_SUCCESS',
  GET_USER_BY_ID_FAIL: 'GET_USER_BY_ID_FAIL',

  CLEAR_ALL: 'CLEAR_ALL',
};
